# You probably shouldn't mess with this file
# edit your environment config files instead

site_name: Phial
domain: phial.dev
admin_email: admin@phial.dev
monolog.name: Phial

login_redirect: account.edit # should be a route name

upload_dir: %app_root%/public/uploads

swiftmailer.options:
    host: localhost
    port: 25
    username: ''
    password: ''
    encryption: ~
    auth_mode: ~

monolog.logfile: %app_root%/log/application.log

db.options:
    dbname: lander
    user: ~
    password: ~
    host: localhost
    driver: pdo_pgsql

session.storage.options:
    name: _phial_sess

assetic.options:
    web: %app_root%/public
    debug: false
    auto_dump: true # turn this off on production sites!
